databases:
  - name: budget-app
    databaseName: budget_app_yf8h
    user: budget_app_yf8h_user

services:
  - type: web
    name: Budget-App
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_yf8h
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false